<?php

namespace App\Repositories\Relationship;

use App\Relationship;
use App\Repositories\EloquentRepository;

class RelationshipRepository extends EloquentRepository implements RelationshipRepositoryInterface
{
    public function __construct(Relationship $relationship)
    {
        $this->model = $relationship;
    }

    public function getListUser($filter)
    {
        return $this->model->getListUser($filter);
    }

    public function createItem($rawData)
    {
        if ($rawData['follower_id'] == $rawData['following_id']) {
            return ['error' => true, 'message' => trans('relationship.validate.duplicate')];
        }
        return parent::createItem($rawData); // TODO: Change the autogenerated stub
    }
}